#!/usr/bin/env bash


set -e
metric_name="SERVICENAME"
unit="Count"
value=$(if [ `ps aux | grep -v grep| grep -v "$0" | grep SERVICENAME | wc -l | awk '{print $1}'` -gt 0 ] ;then echo "1"; else echo "0"; fi)
echo "$metric_name;$unit;$value"

