#!/usr/bin/env bash


set -e
metric_name="URLNAME"
unit="Count"
value=$(if [ `curl  -Is   https://URLNAME|egrep -w '200 OK' |wc -l| awk '{print $1}'` -gt 0 ] ;then echo "1"; else echo "0"; fi)
echo "$metric_name;$unit;$value"

